class_name MCharacterAbilityEffectJump extends MCharacterAbilityEffect

func create_handler(context: MCharacterAbilityExecutionExecuteContext) -> MCharacterAbilityExecutionExecuteEffectHandler:
	return MCharacterAbilityExecutionExecuteJumpHandler.new(context)
