class_name MCharacterAbilityTargetingLocation extends MCharacterAbilityTargeting

func get_strategy(context: MCharacterAbilityExecutionTargetingContext) -> MCharacterAbilityExecutionTargetingBase:
	return MCharacterAbilityExecutionTargetingLocation.new(context)
