class_name MCharacterAbilityTargetingMouseTarget extends MCharacterAbilityTargeting

func get_strategy(context: McharacterAbilityExecutionAimingContext) -> MCharacterAbilityExecutionAimingBase:
	return McharacterAbilityExecutionAimingMouseTarget.new(context)
