class_name MCharacterAbilityTargetingLocation extends MCharacterAbilityTargeting

func get_strategy(context: McharacterAbilityExecutionAimingContext) -> MCharacterAbilityExecutionAimingBase:
	return McharacterAbilityExecutionAimingLocation.new(context)
