class_name MCharacterAbilityTargetingMouseTarget extends MCharacterAbilityTargeting

func get_strategy(context: MCharacterAbilityExecutionTargetingContext) -> MCharacterAbilityExecutionTargetingBase:
	return MCharacterAbilityExecutionTargetingMouseTarget.new(context)
