class_name MCharacterAbilityTargetingLocation extends MCharacterAbilityTargeting

func get_strategy(context: MCharacterAbilityExecutionAimingContext) -> MCharacterAbilityExecutionAimingBase:
	return McharacterAbilityExecutionAimingLocation.new(context)
