class_name MCharacterAbilityTrigger extends Resource

func create_handler(context: MCharacterAbilityExecutionSetupContext) -> MCharacterAbilityExecutionSetupTriggerHandler:
	return MCharacterAbilityExecutionSetupTriggerHandler.new(context)
