class_name MCharacterAbilityEffect extends Resource

func create_handler(context: MCharacterAbilityExecutionExecuteContext) -> MCharacterAbilityExecutionExecuteEffectHandler:
	return MCharacterAbilityExecutionExecuteEffectHandler.new(context)
