class_name CharacterAbilityTargetingLocation extends CharacterAbilityTargeting

func get_strategy(context: CharacterAbilityAimingContext) -> CharacterAbilityExecutionAimingHandler:
	return CharacterAbilityExecutionAimingLocation.new(context)
