class_name CharacterAbilityTargetingMouseTarget extends CharacterAbilityTargeting

func get_strategy(context: CharacterAbilityAimingContext) -> CharacterAbilityExecutionAimingHandler:
	return CharacterAbilityExecutionAimingMouseTarget.new(context)
