class_name CharacterAbilityTriggerChanneled extends CharacterAbilityTrigger

func create_handler(
	blackboard: CharacterAbilityExecutionBlackboard,
) -> CharacterAbilityExecuteTriggerHandler:
	return CharacterAbilityExecuteTriggerChanneledHandler.new(blackboard)
