class_name CharacterAbilityWindup extends Resource

func create_handler(context: CharacterAbilitySetupContext) -> CharacterAbilityExecutionSetupWindupHandler:
	return CharacterAbilityExecutionSetupWindupHandler.new(context)
