class_name CharacterAbilityWindupInstant extends CharacterAbilityWindup

func create_handler(context: CharacterAbilitySetupContext) -> CharacterAbilitySetupWindupHandler:
	return CharacterAbilitySetupInstantHandler.new(context)
