class_name CharacterAbilityWindupInstant extends CharacterAbilityWindup

func create_handler(context: CharacterAbilityExecutionSetupContext) -> CharacterAbilityExecutionSetupWindupHandler:
	return CharacterAbilityExecutionSetupInstantHandler.new(context)
